stages:
  - clean
  - test
  - build

######################################################
# Linux: WickrIO ONLY runs on Linux (Ubuntu)
######################################################
build_cloud_alpha:
  stage: build
  script:
    - bash autobuild.sh cloud alpha
  only:
    - triggers
    - tags
  tags:
    - linux
    - alpha
    - cloud
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_cloud_alpha/*.zip

build_cloud_beta:
  stage: build
  script:
    - bash autobuild.sh cloud beta
  only:
    - tags
  tags:
    - linux
    - beta
    - cloud
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_cloud_beta/*.zip

build_cloud_release:
  stage: build
  script:
    - bash autobuild.sh cloud release
  only:
    - tags
  tags:
    - linux
    - release
    - cloud
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_cloud_release/*.zip

build_messenger_release:
  stage: build
  script:
    - bash autobuild.sh messenger release
  only:
    - tags
  tags:
    - linux
    - release
    - messenger
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_messenger_release/*.zip

test_messenger_beta:
  stage: test
  script:
    - bash autobuild.sh messenger beta
    - bash autotest.sh messenger beta
  tags:
    - linux
    - release
    - messenger
