stages:
  - clean
  - test
  - build

######################################################
# Linux: WickrIO ONLY runs on Linux (Ubuntu)
######################################################

#
# Cloud builds
#
build_cloud_alpha:
  stage: build
  script:
    - bash autobuild.sh cloud alpha
  only:
    - triggers
    - tags
  tags:
    - linux
    - alpha
    - cloud

build_cloud_beta:
  stage: build
  script:
    - bash autobuild.sh cloud beta
  only:
    - tags
  tags:
    - linux
    - beta
    - cloud

build_cloud_release:
  stage: build
  script:
    - bash autobuild.sh cloud release
  only:
    - tags
  tags:
    - linux
    - release
    - cloud
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_cloud_release/*.zip

#
# Enterprise builds
#
build_enterprise_alpha:
  stage: build
  script:
    - bash autobuild.sh enterprise alpha
  only:
    - triggers
    - tags
  tags:
    - linux
    - alpha
    - enterprise
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_enterprise_alpha/*.zip

build_enterprise_release:
  stage: build
  script:
    - bash autobuild.sh enterprise release
  only:
    - tags
  tags:
    - linux
    - release
    - enterprise
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_enterprise_release/*.zip

#
# Messenger builds
#
build_messenger_alpha:
  stage: build
  script:
    - bash autobuild.sh messenger alpha
  only:
    - tags
  tags:
    - linux
    - alpha
    - messenger
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_messenger_alpha/*.zip

build_messenger_release:
  stage: build
  script:
    - bash autobuild.sh messenger release
  only:
    - tags
  tags:
    - linux
    - release
    - messenger
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/wickrio_messenger_release/*.zip

#
# Tests
#
#test_messenger_beta:
#  stage: test
#  script:
#    - bash autobuild.sh messenger beta
#    - bash autotest.sh messenger beta
#  tags:
#    - linux
#    - release
#    - messenger
