stages:
  - clean
  - test
  - build

######################################################
# Mac
build_mac:
  stage: build
  script:
    - bash autobuild.sh
  only:
    - tags
  tags:
    - macos

test_mac:
  stage: test
  script:
    - bash autobuild.sh
    - bash autotest.sh
  tags:
    - macos

######################################################
# Windows
build_win:
  stage: build
  script:
    - bash autobuild.sh
  tags:
    - windows

test_win:
  stage: test
  script:
    - bash autobuild.sh
    - bash autotest.sh
  tags:
    - windows

######################################################
# Linux
build_linux:
  stage: build
  script:
    - bash autobuild.sh
  only:
    - tags
  tags:
    - linux
  artifacts:
    expire_in: 1 week
    paths:
      - autobuild-output/compliance.deploy/*.zip

test_linux:
  stage: test
  script:
    - bash autobuild.sh
    - bash autotest.sh
  tags:
    - linux
