stages:
  - clean
  - test
  - build

######################################################
# Linux: WickrIO ONLY runs on Linux (Ubuntu)
######################################################

#
# Cloud builds
#
build_cloud_alpha:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh cloud alpha
  only:
    - triggers
    - tags
  tags:
    - linux
    - alpha
    - cloud
    - docker

build_cloud_beta:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh cloud beta
  only:
    - tags
  tags:
    - linux
    - beta
    - cloud
    - docker

build_cloud_release:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh cloud release
  only:
    - tags
  tags:
    - linux
    - release
    - cloud
    - docker

#
# Enterprise builds
#
build_enterprise_alpha:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh enterprise alpha
  only:
    - triggers
    - tags
  tags:
    - linux
    - alpha
    - enterprise
    - docker

build_enterprise_release:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh enterprise release
  only:
    - tags
  tags:
    - linux
    - release
    - enterprise
    - docker

#
# Messenger builds
#
build_messenger_alpha:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh messenger alpha
  only:
    - tags
  tags:
    - linux
    - alpha
    - messenger
    - docker

build_messenger_beta:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh messenger beta
  only:
    - tags
  tags:
    - linux
    - beta
    - messenger
    - docker

build_messenger_release:
  stage: build
  before_script:
    - bash PREP-FOR-AUTOBUILD
  script:
    - bash autobuild.sh messenger release
  only:
    - tags
  tags:
    - linux
    - release
    - messenger
    - docker

#
# Tests
#
#test_messenger_beta:
#  stage: test
#  script:
#    - bash autobuild.sh messenger beta
#    - bash autotest.sh messenger beta
#  tags:
#    - linux
#    - release
#    - messenger
