stages:
  - clean
  - test
  - build

######################################################
# Mac
build_mac:
  stage: build
  script:
    - bash autobuild.sh
  only:
    - tags
  tags:
    - macos

test_mac:
  cache:
    paths:
    - build/
  stage: test
  script:
    - bash autobuild.sh
    - bash autotest.sh
  tags:
    - macos

######################################################
# Windows
build_win:
  cache:
    paths:
    - build/
  stage: build
  script:
    - bash autobuild.sh
  tags:
    - windows

test_win:
  cache:
    paths:
    - build/
  stage: test
  script:
    - bash autobuild.sh
    - bash autotest.sh
  tags:
    - windows

######################################################
# Linux
build_linux:
  stage: build
  script:
    - bash autobuild.sh
  only:
    - tags
  tags:
    - linux

test_linux:
  cache:
    paths:
    - build/
  stage: test
  script:
    - bash autobuild.sh
    - bash autotest.sh
  tags:
    - linux
